### PR TITLE
Some changes to suppress compiler warnings on function inlining and unused variables

### PR DESCRIPTION
**Pull request by plpolak**

### CODE REVIEW

**Comment by uschuster** [comment]
I do **not** support **merging** commit https://github.com/SynEdit/SynEdit/pull/34/commits/e5973e9bad20a0114b79f0dcde43ec937539c4e4 !

Inlining is supported since Delphi 9/2005 and not since XE3! Using units to avoid the H2443 hint is unit and version specific. Each unit required to avoid the H2443 hint depends on the lowest version of Delphi that uses the inline directive for a used method.

**Comment by plpolak** [comment]
Unfortunately I am not actively using all those Delphi versions (only XE3 and 10.1 for the moment). Maybe it is better to disable H2443 in the SynEdit units, to avoid unnecessary warnings then. They can be really confusing when compiling large projects (and hints can provide useful information)

**Comment by uschuster** [comment]
I have a lot more versions installed, have almost all command line compilers, will look into that topic and make a proposal in my fork.

**Comment by uschuster** [comment]
I have made a proposal in my fork and added a pull request. There would have been another issue with that pull request here - it would have broken compilation with pre Unicode versions as these use as well FileNameW in TCustomSynEdit.WMDropFiles.

**Comment by uschuster** [comment]
I have merged the Oracle SQL highlighting commits 85b4617b480c1269f173c1f45915a26e8121f0a2 and 030043d8479786b5ac070d11b2b578bf5df7e1f6 with cherry-picking, because the pull request contains unwanted changes -> close pull request.

**Pull request closed without merging**
